scheduler:
    algorithm: "value iteration"
    function: "table"
    mode: "non-preemptive"

environment:
    mode: "non-preemptive"
    num_machines: 1
     
job_generator:
    episodes: 1
    generation_scheme: "single"
    name: "uniform"
    job_horizon: 10
    parameters:
        new: 0.5
        low: 2
        high: 5
        func: "lambda x: x * x"
