common:
    schedule_mode: "non-preemptive"
    train_mode: "offline"

scheduler:
    algorithm: "value iteration"
    function: "table"

environment:
    episodes: 100
    num_machines: 1
     
job_generator:
    name: "uniform"
    train:
        job_horizon: 10
        num_sequences: 1
    evaluate:
        job_horizon: 10
        num_sequences: 1
    parameters:
        new: 0.5
        low: 2
        high: 5
        func: "lambda x: x * x"
